name: Live EPG

on:
  schedule:
    - cron: '0 3 */2 * *'  # Run at 3am every 2 days
  workflow_dispatch:

jobs:
  scrape_and_generate_epg:
    name: Scrape TV Programming and Generate EPG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - name: Run EPG Script
        run: |
          python py/tvxml.py --days 3 > en/tv.xml
        env:
          TZ: America/New_York

      - name: Compress XML with gzip (retain original)
        run: |
          gzip -c en/tv.xml > en/tv.xml.gz

      - name: Stash changes, pull latest, and apply stash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || true

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          file_pattern: en/tv.xml en/tv.xml.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
